export type ModalSection = 'work' | 'about' | 'process' | 'services' | 'contact' | null;

export interface KeycapConfig {
  id: string;
  char: string;
  isSpecial?: boolean;
  specialIcon?: 'star' | 'return';
  label: string;
  subtitle: string;
  screenTitle: string;
  screenDesc: string;
  destination: ModalSection;
  centreX: number;
  centreY: number;
  width: number;
  height: number;
  color: string;
  baseColor: string;
  inkColor: string;
  fontSize: string;
}

export const KEYCAPS: KeycapConfig[] = [
  // Top Row (P O R T F)
  {
    id: 'key-p',
    char: 'P',
    label: 'SELECTED WORK',
    subtitle: 'Browse featured projects & identity concepts',
    screenTitle: 'SELECTED WORK',
    screenDesc: 'Selected website and identity concepts.',
    destination: 'work',
    centreX: 379,
    centreY: 590,
    width: 156,
    height: 130,
    color: '#EC6426',
    baseColor: '#AD4017',
    inkColor: '#4A1C0F',
    fontSize: 'text-2xl sm:text-3xl font-extrabold',
  },
  {
    id: 'key-o-top',
    char: 'O',
    label: 'ABOUT ME',
    subtitle: 'Bio, creative direction & philosophy',
    screenTitle: 'ABOUT ME',
    screenDesc: 'Welcome to my portfolio. A little personality.',
    destination: 'about',
    centreX: 580,
    centreY: 580,
    width: 156,
    height: 130,
    color: '#F8A91F',
    baseColor: '#BC7512',
    inkColor: '#522A07',
    fontSize: 'text-2xl sm:text-3xl font-extrabold',
  },
  {
    id: 'key-r',
    char: 'R',
    label: 'MY PROCESS',
    subtitle: 'From conversation to production launch',
    screenTitle: 'MY PROCESS',
    screenDesc: 'We start with a conversation, shape the design together.',
    destination: 'process',
    centreX: 782,
    centreY: 570,
    width: 156,
    height: 130,
    color: '#FDE3CF',
    baseColor: '#CAA58A',
    inkColor: '#66271B',
    fontSize: 'text-2xl sm:text-3xl font-extrabold',
  },
  {
    id: 'key-t',
    char: 'T',
    label: 'WHAT I DO',
    subtitle: 'Services, full-stack design & engineering',
    screenTitle: 'WHAT I DO',
    screenDesc: 'Thoughtful design, clear communication.',
    destination: 'services',
    centreX: 982,
    centreY: 559,
    width: 156,
    height: 130,
    color: '#2E573A',
    baseColor: '#193A23',
    inkColor: '#FDE3CF',
    fontSize: 'text-2xl sm:text-3xl font-extrabold',
  },
  {
    id: 'key-f',
    char: 'F',
    label: 'EXPLORE',
    subtitle: 'Dive deep into interactive showcases',
    screenTitle: 'EXPLORE',
    screenDesc: 'Explore interactive digital experiences.',
    destination: 'work',
    centreX: 1184,
    centreY: 548,
    width: 156,
    height: 130,
    color: '#72AC43',
    baseColor: '#487A26',
    inkColor: '#1A330B',
    fontSize: 'text-2xl sm:text-3xl font-extrabold',
  },

  // Lower Row (O L I O ★ LET'S TALK)
  {
    id: 'key-o-low1',
    char: 'O',
    label: 'A LITTLE ABOUT ME',
    subtitle: 'Curious mind building digital experiences',
    screenTitle: 'A LITTLE ABOUT ME',
    screenDesc: 'A curious mind. A lot of possibility.',
    destination: 'about',
    centreX: 355,
    centreY: 783,
    width: 98,
    height: 108,
    color: '#E4A5CA',
    baseColor: '#B76F9B',
    inkColor: '#5E1B46',
    fontSize: 'text-lg sm:text-xl font-bold',
  },
  {
    id: 'key-l',
    char: 'L',
    label: 'THE PROCESS',
    subtitle: 'Iterative, collaborative design engineering',
    screenTitle: 'THE PROCESS',
    screenDesc: 'Shape the design together, build and launch.',
    destination: 'process',
    centreX: 479,
    centreY: 776,
    width: 98,
    height: 108,
    color: '#66271B',
    baseColor: '#40150E',
    inkColor: '#FDE3CF',
    fontSize: 'text-lg sm:text-xl font-bold',
  },
  {
    id: 'key-i',
    char: 'I',
    label: 'MY APPROACH',
    subtitle: 'High craft, performance & accessibility',
    screenTitle: 'MY APPROACH',
    screenDesc: 'Websites built around your business goals.',
    destination: 'services',
    centreX: 602,
    centreY: 770,
    width: 98,
    height: 108,
    color: '#EC6426',
    baseColor: '#AD4017',
    inkColor: '#4A1C0F',
    fontSize: 'text-lg sm:text-xl font-bold',
  },
  {
    id: 'key-o-low2',
    char: 'O',
    label: 'SAY HELLO',
    subtitle: 'Have a project in mind or want to say hi?',
    screenTitle: 'SAY HELLO',
    screenDesc: 'Good design starts with hello.',
    destination: 'contact',
    centreX: 728,
    centreY: 763,
    width: 98,
    height: 108,
    color: '#F8A91F',
    baseColor: '#BC7512',
    inkColor: '#522A07',
    fontSize: 'text-lg sm:text-xl font-bold',
  },
  {
    id: 'key-star',
    char: '★',
    isSpecial: true,
    specialIcon: 'star',
    label: 'PORTFOLIO',
    subtitle: 'Explore full catalog of creative work',
    screenTitle: 'Explore my portfolio',
    screenDesc: 'Explore my portfolio of creative web engineering.',
    destination: 'work',
    centreX: 852,
    centreY: 756,
    width: 98,
    height: 108,
    color: '#E4A5CA',
    baseColor: '#B76F9B',
    inkColor: '#5E1B46',
    fontSize: 'text-lg sm:text-xl font-bold',
  },
  {
    id: 'key-contact-bar',
    char: "LET'S TALK",
    isSpecial: true,
    specialIcon: 'return',
    label: "LET'S TALK",
    subtitle: 'Send a note or schedule a conversation',
    screenTitle: "LET'S TALK",
    screenDesc: 'Have a project in mind, or just want to say hi?',
    destination: 'contact',
    centreX: 1135,
    centreY: 745,
    width: 374,
    height: 112,
    color: '#252525',
    baseColor: '#101010',
    inkColor: '#FFFFFF',
    fontSize: 'text-xs sm:text-sm font-semibold tracking-wider',
  },
];
